version: '3'
services:
  backend:
    build: ./Backend
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env
    restart: always
    networks:
      - app-network

  frontend:
    build: ./Frontend
    ports:
      - "3000:3000"
    env_file:
      - ./Frontend/.env.local
    volumes:
    - ./Frontend:/app
    command: sh -c "npm run build && npm start"
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
