import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await page.getByRole('link', { name: 'Sign-In', exact: true }).click();
  await page.getByRole('textbox', { name: 'Email or Telephone' }).click();
  await page.getByRole('textbox', { name: 'Email or Telephone' }).fill('oak@user.com');
  await page.getByRole('textbox', { name: 'Email or Telephone' }).press('Tab');
  await page.getByRole('textbox', { name: 'password' }).fill('123456');
  await page.getByRole('textbox', { name: 'password' }).press('Enter');
  await page.getByRole('button', { name: 'Sign-In' }).click();
  await page.locator('.hdcard_white > img').click();
  await page.locator('body > div:nth-child(4)').click();
  await page.getByRole('link', { name: 'My-booking' }).click();
  await page.locator('.bg-blue-500').first().click();
  await page.getByRole('button', { name: 'Select This Room' }).first().click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('3');
  await page.locator('div').filter({ hasText: /^Number of People$/ }).click();
  await page.locator('div').filter({ hasText: /^Check-in Date$/ }).getByRole('textbox').fill('2025-04-23');
  await page.locator('div').filter({ hasText: /^Check-in Date$/ }).click();
  await page.locator('div').filter({ hasText: /^Check-out Date$/ }).getByRole('textbox').fill('2025-04-25');
  await page.getByRole('button', { name: 'Update Booking' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  await expect(page.getByRole('rowgroup')).toContainText('3 guests');
  await expect(page.getByRole('rowgroup')).toContainText('$855.55 / night');
  await expect(page.getByRole('rowgroup')).toContainText('4/23/2025');
  await expect(page.getByRole('rowgroup')).toContainText('4/25/2025');
});